### ISSUE TITLE
PlayConfigurationInjector example

### ISSUE THREAD

**Issue by albertshift** [scaldi/scaldi-play-example#5]
In the documentation http://scaldi.org/learn/
you mentioned that it is possible to create PlayConfigurationInjector to access application.conf properties.

```
class PlayConfigurationInjector(app: => Application) extends RawInjector {
  def getRawValue(name: String) = app.configuration.getString(name)
}
```

I did not find this ability in 'scaldi-play-example'.

**Comment by OlegIlyenko** [comment]
It's probably not very obvious on the first sight, but example application actually uses this feature. There are several places where it's used, for example here:

https://github.com/scaldi/scaldi-play-example/blob/master/app/service/ServerStatusService.scala#L6

`configNumbers` injected from `conf/application.conf`:

https://github.com/scaldi/scaldi-play-example/blob/master/conf/application.conf#L47

`PlayConfigurationInjector` is also available out-of-the-box, so you don't need to do anything special to enable it.

**Comment by albertshift** [comment]
This is does not work.

**Comment by OlegIlyenko** [comment]
What do you mean? Have you tried inject properties from `application.conf` in your project and it didn't worked (you got an exception)? I would appeared if you could provide more details about the issue you are facing.

Recent versions of scaldi-play use improved version of this injector, which also able to handle additional property types supported by typesafe-config:

http://scaldi.org/learn/#typesafe-config-injector

So this `PlayConfigurationInjector` example is a little bit outdated. I think I need to update it.

**Comment by albertshift** [comment]
For the inside the Module:
val cassandraHost = inject [String]  ("cassandra.host")

Caused by: scaldi.InjectException: No binding found with following identifiers:
  * TypeTagIdentifier(String)
  * StringIdentifier(cassandra.host)
	at scaldi.Injectable$class.noBindingFound(Injectable.scala:46) ~[scaldi_2.11-0.5.6.jar:0.5.6]

**Comment by OlegIlyenko** [comment]
just to be 100% sure:

* you are using in in play 2.4.0 application with **scaldi-play** v0.5.6 dependency
* "property.name" is defined in `conf/application.conf`
* You also have `play.application.loader = scaldi.play.ScaldiApplicationLoader` there, in addition to your application's modules (which are added to `play.modules.enabled`)
* you get this exception when you start your application with `sbt run`

Are these statements true in your case? If yes, then I would really appreciate if you could share a reduced example of the application that reproduces this issue, so that i could look into it.

**Comment by albertshift** [comment]
No, I am using v0.5.7 scaldi-play, play is 2.4.0, sbt 0.13.8
property,name is defined in conf/application.conf
play.application.loader = scaldi.play.ScaldiApplicationLoader & play.modules.enabled are defined in application.conf
starting application by 'activator run'

Key point is that I am trying access props in Module, not in Service like in your example.
Also I found that injection to Module does not work, I can not inject [Application]

Now I an using workaround with 'typesafe-config', it works.

**Comment by OlegIlyenko** [comment]
I just had an idea... since you are injecting property inside of the module like this:

    val localValue = inject [String]  ("property.name")

then maybe you could try to define `lazy val localValue = ...` or `def localValue = ...` instead. `val` means eager evaluation, so the whole module would be forced to initialize in the middle of binding definition. `lazy val` or `def` will postpone the injection.

**Comment by albertshift** [comment]
lazy works! but it have to be in all vals, even those who are using localValue

**Comment by OlegIlyenko** [comment]
Nice! Glad that it solves thew issue. Yeah, laziness is kind of transitive

**Comment by albertshift** [comment]
Probably, you have to add this to the documentation, it is not so obvious. And remove PlayConfigurationInjector by mentioning that all props from application.conf are available by default in context.

**Comment by OlegIlyenko** [comment]
Yes, definitely. I will add these thing in the docs.
